package selenium_tests;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class LoginGmail extends FunctionalTest {

    @Test
    public void signUp() {

        driver.get("http://gmail.com");

        LoginPage loginPage = new LoginPage(driver);

        assertTrue(loginPage.isInitialized());
        loginPage.enterUserEmail("TestingSMUser@gmail.com");

        assertTrue(loginPage.isPasswordInitialized());
        loginPage.enterUserPassword("22F5##yNt6j7");

        InboxPage inboxPage = loginPage.nextOnPassword();

        inboxPage.newMail();
        inboxPage.fillToField("misticosmisticos@gmail.com");//smarkov@lohika.com
        inboxPage.fillSubjectField("Hello Appium Automation Course from Stanislav");


        MailWindow mailWindow = inboxPage.fillBodyOfEmail("This mail was generated by Automation code");
        mailWindow.sendButton();
        inboxPage.sentFolder();

        assertEquals("Hello Appium Automation Course from", inboxPage.summarySentEmail());

    }
}
