package selenium_tests;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class LoginGmail extends FunctionalTest {

    @Test
    public void signUp() {

        driver.get("http://gmail.com");

        LoginPage loginPage = new LoginPage(driver);

        assertTrue(loginPage.isInitialized());
        loginPage.enterUserEmail("");

        assertTrue(loginPage.isPasswordInitialized());
        loginPage.enterUserPassword("");

        InboxPage inboxPage = loginPage.nextOnPassword();

        inboxPage.newMail();
        inboxPage.fillToField("smarkov@lohika.com");
        inboxPage.fillSubjectField("Hello Appium Automation Course from Stanislav");
        inboxPage.fillBodyOfEmail("This mail was generated by Automation code");
        inboxPage.sendButton();
        inboxPage.sentFolder();

        assertTrue(inboxPage.summaryOfSentEmail());
    }
}
